### ISSUE TITLE
Problem with login step

### ISSUE THREAD

**Issue by bsergean** [metcalfc/docker-action-examples#3]
Hi there,

I'm trying to setup something for an open-source library hosted on my company space. I am getting an [error](https://github.com/machinezone/IXWebSocket/runs/1063249282?check_suite_focus=true) though when my action runs at the login step, talking about a missing password.

```
 Login to GitHub Package Registry
0s
    logout: true
Run docker/login-action@v1
  with:
    registry: ghcr.io
    username: machinezone
    logout: true
##[error]Input required and not supplied: password
```

I used this, hoping that the secret would be populated, following this [blog post](https://www.docker.com/blog/docker-support-for-the-new-github-container-registry/).

```
        name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
```

The full yaml for the github action is [here](https://github.com/machinezone/IXWebSocket/blob/master/.github/workflows/docker.yml).

Any clue on what might be going on ?
Should I report that on the github login action instead maybe ... ?
