### ISSUE TITLE
One repository(One folder) manage multiple images how to sit context?

### ISSUE THREAD

**Issue by HiColinn** [metcalfc/docker-action-examples#8]
Like fllow pic,I manage multiple docker images on one repository,so how to write the context? I get the image name from git push message.
![2021-03-17_090716](https://user-images.githubusercontent.com/65964332/111399632-b288ed80-8700-11eb-93d2-85659ba07000.jpg)

**Comment by metcalfc** [comment]
You can use multiple build stanzas.

```
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./app
          file: ./app/Dockerfile
          target: prod
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
```

The `context` and `file` parameters can be pointed to your various `alpine-base` and `alpine-full` directories.

**Comment by HiColinn** [comment]
Hi,it is also doesn't work,this is my build yml:
```
name: Build Docker Image
on:
  push:
    branches:
        - master
jobs:
    build:
        # 命名工作
        name: Build docker image
        # 指定工作环境
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            -   name: Filter image name
                #获取提交日志中的变量并设置到env中
                run: |
                    ```Get push messages and get var```
            # QEMU
                uses: docker/setup-qemu-action@v1
            # Buildx
            -   name: Set up Docker Buildx
                id: buildx
                uses: docker/setup-buildx-action@v1
            # 登录Dockerhub
            -   name: Login to DockerHub
                uses: docker/login-action@v1 
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            # 构建镜像并推送到Docker Hub
            -   name: Build and push
                if: ${{ env.IMAGE_NAME != '' }}
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    builder: ${{ steps.buildx.outputs.name }}
                    context: ./${{ env.IMAGE_NAME }}
                    file: ./${{ env.IMAGE_NAME }}/Dockerfile
                    target: prod
                    push: true
                    tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG_NAMES }}
```
  And this is the build logs:
![2021-03-19_054747](https://user-images.githubusercontent.com/65964332/111702474-454b9880-8877-11eb-9278-673c9f48b8f1.jpg)
```
Run docker/build-push-action@v2
📣 Buildx version: 0.5.1
🏃 Starting build...
/usr/bin/docker buildx build --tag ***/alpine-base:latest --tag 5.2.1 --target prod --iidfile /tmp/docker-build-push-Oqs8WE/iidfile --file ./alpine-base/Dockerfile --builder builder-29ce8a5b-ce1c-4013-a495-32c52e8a9cf1 --push ./alpine-base
error: unable to prepare context: path "./alpine-base" not found
Error: buildx call failed with: error: unable to prepare context: path "./alpine-base" not found
```

**Comment by metcalfc** [comment]
I'm guessing the error is something unrelated to the action. Consider testing it with hardcoded values as a check. But here is a quick example I whipped up with two images in the same repository. 

https://github.com/metcalfc/two-build-pushes/blob/main/.github/workflows/main.yml

If you're still having issues, I suggest going to the [Docker Community Slack](http://dockr.ly/slack) and asking in the `#github_actions` channel.

**Comment by HiColinn** [comment]
> I'm guessing the error is something unrelated to the action. Consider testing it with hardcoded values as a check. But here is a quick example I whipped up with two images in the same repository.
> 
> https://github.com/metcalfc/two-build-pushes/blob/main/.github/workflows/main.yml
> 
> If you're still having issues, I suggest going to the [Docker Community Slack](http://dockr.ly/slack) and asking in the `#github_actions` channel.

I am a chinese,so ....the Community Slack ,I hope you can help me ,thank you very much

**Comment by 70599** [comment]
@metcalfc 
Got same error here.
Workflow yaml file (hardcoded context path):
```yaml
- name: Build and push
      id: build_php_fpm
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./php-fpm
        file: ./php-fpm/Dockerfile
        platforms: linux/amd64,linux/armhf
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/php-fpm
```

Error message:
`buildx failed with: error: unable to prepare context: path "./php-fpm" not found`
